services:
  garage:
    image: dxflrs/garage:v2.0.0
    container_name: garage
    volumes:
      - ./dev.local/garage.toml:/etc/garage.toml
      - ./dev.local/meta:/var/lib/garage/meta
      - ./dev.local/data:/var/lib/garage/data
    restart: unless-stopped
    ports:
       - 3900:3900
       - 3901:3901
       - 3902:3902
       - 3903:3903

