services:
  garage:
    image: dxflrs/garage:v2.0.0
    container_name: garage
    volumes:
      - ./dev.local/garage.toml:/etc/garage.toml
      - ./dev.local/meta:/var/lib/garage/meta
      - ./dev.local/data:/var/lib/garage/data
    restart: unless-stopped
    ports:
       - 3900:3900
       - 3901:3901
       - 3902:3902
       - 3903:3903

  webui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: garage-webui
    restart: unless-stopped
    volumes:
      - ./dev.local/garage.toml:/etc/garage.toml:ro
    ports:
      - 3909:3909
    environment:
      API_BASE_URL: "http://garage:3903"
      S3_ENDPOINT_URL: "http://garage:3900"
      AUTH_USER_PASS: "admin:$2y$10$2i1DScIpTap7oB6KEYLP7um9/ms6LBf.TBzuqfSWRdRMvWRe35Y0S" #admin:admin

